[package]
name = "alias_manager"
version = "0.1.0"
authors = ["Nekzus"]
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
console = "0.15.8"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
dirs = "5.0.1"
